Fixes for Windows

diff --git a/run_after_init.bat.tmpl b/run_after_init.bat.tmpl
--- a/run_after_init.bat.tmpl
+++ b/run_after_init.bat.tmpl
@@ -3,7 +3,7 @@
 
 where nu >nul 2>&1
 if errorlevel 1 (
-    echo Error: nushell (nu) is not installed or not in PATH >&2
+    echo "Error: nushell (nu) is not installed or not in PATH >&2"
     exit /b 1
 )
 
